### ISSUE TITLE
Where are the balsa machining nose cones stored?

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#7] opened 2022-03-18 21:58 UTC
I can't find any of the Balsa Machining nose cone source.

**Comment by ghost** [comment] 2022-03-18 22:33
Actually I would like to know where all of the manufactures items sourced. I coukd not fine FlisKits, LOC, or Giant Leap either.

**Comment by dbcook** [comment] 2022-03-21 23:19
Sorry for late reply, I've been on vacation for a few days.

LOC is fully covered in loc_precision.orc, so I'm not sure what the issue is with that one.

There are various comments about the other manufacturers in the README.  Some recap:

BMS: A wide majority of the tubes and nose cones are clones of Estes/Semroc/eRockets parts.  There are some that are unique to BMS, but picking them all out will be a fair amount of work; comparing the effort needed to part prevalence argues for low priority.  Also there is a data provenance problem because BMS does not list masses for any of their parts.

FlisKits: similar situation as BMS - there are not too many really unique parts apart from some nose cones.  The tube sizes are all Estes (except the BT-2 which matches Semroc T-1+).  There are several nose cones that could be filled in, but there are data problems including some missing masses, missing shoulder lengths for transitions, and broken image links in the wayback machine for some "special" shape nose cones.  Fliskits was sold in 2019 and the new owners are no longer listing any parts at all.

Giant Leap: This one needs to be done somehow since they are and have been the only real source of phenolic tubes.  Back when the project started I couldn't find any authoritative data (they have never issued a catalog that I have found), but there is now some limited info on their website.  There is still a major data provenance issue as the website only lists the outside diameters of tubes; inside diameter and weight are missing everywhere.  Nose cone data only gives the exposed length and OD; shoulder length and mass are missing.  As of today I put back the legacy OR 15.x file back into the build, but nothing has been updated or verified, and this data must be considered unofficial and mostly unsubstantiated.

**Comment by ghost** [comment] 2022-03-23 19:00
I understand all you said above. I just wanted to know what ORC contains what you do have since OR clearly has BMS, FlisKits, and Giant Leap. They must be stored somewhere.

**Comment by dbcook** [comment] 2022-08-16 21:03
Closing this issue specifically for BMS due to insufficient verifiable data from the manufacturer.   One of my base principles for this database is to only publish verifiable data, either from the manufacturer or from measurement of actual parts of known origin.  The old OR had a BMS file but I have not been able to establish the provenance of that data.  The main issue with the currently available specs is shoulder lengths.  On the current BMS website (reviewed Aug 2022), shoulder lengths for many nose cones can only be obtained by measuring low-res drawings, and some are missing entirely.  Only 6 out of 20 transitions have shoulder lengths given.

BTW Giant Leap is now included in the new database.

**Closed as completed by dbcook** 2022-08-16 21:03 UTC
